### ISSUE TITLE
resource name may not be empty

### ISSUE THREAD

**Issue by rlex** [jlclx/runtimeclass-controller#1]
Hello! Was looking for something like this project.

Installed as per docs, annotated namespace with
```
kubectl label namespace ingress-nginx runtimeclassname-default=gvisor-hostnetwork
```

Ingress containers still running with default runc, logs contain nothing but 

```
E0102 21:00:01.200006       1 main.go:112] resource name may not be empty
```

Any ideas where to dig?

**Comment by rlex** [comment]
Oh huh, my bad. It seems it will only affect freshly deployed workloads, not existing even if you force-sync chart / restart workloads?

**Comment by jlclx** [comment]
> Hello! Was looking for something like this project.
> 
> Installed as per docs, annotated namespace with
> 
> ```
> kubectl label namespace ingress-nginx runtimeclassname-default=gvisor-hostnetwork
> ```
> 
> Ingress containers still running with default runc, logs contain nothing but
> 
> ```
> E0102 21:00:01.200006       1 main.go:112] resource name may not be empty
> ```
> 
> Any ideas where to dig?

I *think* I recall that error being an ignorable warning, I've not had it affect my functionality.



> Oh huh, my bad. It seems it will only affect freshly deployed workloads, not existing even if you force-sync chart / restart workloads?

Correct, it'll only affect workload objects that are newly applied. 

Unfortunately, even if we wanted to modify an existing workload object, runtimeClassName is not an object property that is modifiable once the object exists.

You would get:

```
# * spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
#   core.PodSpec{
#       ... // 24 identical fields
#       DNSConfig:                 nil,
#       ReadinessGates:            nil,
# -     RuntimeClassName:          &"kata-containers",
# +     RuntimeClassName:          nil,
#       Overhead:                  nil,
#       EnableServiceLinks:        &true,
#       TopologySpreadConstraints: nil,
#   }
```

on attempting to modify an existing object's runtimeClass.

**Comment by rlex** [comment]
Yep, after recreating object it works as expected

>I think I recall that error being an ignorable warning, I've not had it affect my functionality.

Judging by number of lines, it prints that message on every namespace which doesn't have runtimeclassname-default label, or so it seems.

**Comment by jlclx** [comment]
Is the log generation excessive? I'll take a look into making it quieter after I have my lunch if so, since it should be a quick fix

**Comment by rlex** [comment]
Nope, not really excessive. They are here, but not really aggressive.

**Comment by jlclx** [comment]
Seems to be resolved now that I reduced the scope of the webhook via the namespace selector in:
https://github.com/jlclx/runtimeclass-controller/commit/7239ed83d5b6ebbc450dd07e00d957f4043f9678
