### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by rlex** [jlclx/runtimeclass-controller#2]
Hello, maybe you might be interested, i did helm chart for runtimeclass-controller: https://github.com/rlex/helm-charts/tree/master/charts/runtimeclass-controller

P.S. Maybe you can cut non-"latest" version (ie 0.1.0) so it will be easier to keep track on updates?

**Comment by jlclx** [comment]
An *extremely late* reply, sorry.
Ended up rolling my own helm chart.
Thank you for the suggestion.

**Comment by rlex** [comment]
oh good, i can probably deprecate my chart then, since there is official one

**Comment by jlclx** [comment]
I just looked at your chart, you seem to have implemented more configurability than I did (eg, user suppliable TLS certs).
I'm considering merging yours into mine.

**Comment by rlex** [comment]
sure, take any parts you want

**Comment by jlclx** [comment]
Thank you.
